version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:16  # Node.js version
    working_directory: ~/SimpleApplication

jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install npm dependencies
          command: npm install --unsafe-perm
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run Tests
          command: npm test

  e2e_tests:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install --unsafe-perm
      - run:
          name: Install Playwright
          command: npx playwright install
      - run:
          name: Run Playwright Tests
          command: npx playwright test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: main
      - e2e_tests:
          requires:
            - build