version: 2.1

workflows:
  version: 2 # CircleCI 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: main  # Run CI only on the main branch

jobs:
  build:
    docker:
      - image: circleci/node:16  # Updated Node.js version
    working_directory: ~/SimpleApplication
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'npm install npm@8 --no-save'  # Install locally without global update
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install npm dependencies
          command: npm install --unsafe-perm
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run Tests  # Skip if no tests exist
          command: '[ -d test ] && npm test || echo "No tests found, skipping."'
