version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: main  # Run CI only on the main branch

jobs:
  build:
    docker:
      - image: circleci/node:16  # Updated Node.js version
    working_directory: ~/SimpleApplication
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'  # Installs the latest npm version
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install npm dependencies
          command: npm install --unsafe-perm
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run Tests  # Optional - Enable if you have tests
          command: npm test
